# NumPy Practice (Feb 15th- 2026)

# ARRAYS

In [ ]:
import numpy as np

List = [1,2,3,4,5]

arr = np.array(List)

print(List)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
arr_2 = np.array([1,2,3,4,5,6,7,8,9,10])

arr_2[0] = 20
a= arr_2[4:]
a[0] = 25

print(arr_2)
print(a)

[20  2  3  4 25  6  7  8  9 10]
[25  6  7  8  9 10]


In [ ]:
# Properties of an array
arr = np.zeros([2,3])

np.shape(arr_2)  # How many elements in each dimension
np.size(arr_2)   # It gives the size of array (Like total numbers of an elements)
np.ndim(arr_2)   # How many dimensions in an array
arr_2.dtype      # It gives the which datatype in the array

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Array slicing

arr = np.array([10,20,30,40,50])
print(arr[::2])

[10 30 50]


In [ ]:
# Create an array and do the properties of an array

arr_3 = np.array([1,2,3,4,5])

np.shape(arr_3)
np.size(arr_3)
np.ndim(arr_3)

# print(arr_3)

1

In [ ]:
# Indexing an Array
a = arr_3[0]
b = arr_3[-1]
print(a)
print(b)

1
5


In [ ]:
# Slicing an Array

a = arr_3[:3]
b= arr_3[-2:]

print(a)
print(b)

[1 2 3]
[4 5]


In [ ]:
# Multiply the all values through vectorization

arr_3 = np.array([1,2,3,4,5])

mul  = arr_3 * 5
add  = arr_3 + 2
sub  = arr_3 - 1

print(mul)
print(add)
print(sub)

[ 5 10 15 20 25]
[3 4 5 6 7]
[0 1 2 3 4]


In [ ]:
# creating an array by doing aggregation

arr_4 = np.array([12,13,14,27,15,16,17])

mean = np.mean(arr_4)
sum = np.sum(arr_4)
min = np.min(arr_4)
max = np.max(arr_4)

print(mean)
print(sum)
print(min)
print(max)

16.285714285714285
114
12
27


PHASE -1 PRACTICE - (Feb-17th-2026)

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [ ]:
# Task 2 — Array Properties

a = np.shape(arr)
b = np.size(arr)
c = np.ndim(arr)
d = arr.dtype

print(a)
print(b)
print(c)
print(d)

(5,)
5
1
int64


In [ ]:
# Task 3 — Indexing Practice
arr2 = np.array([100, 200, 300, 400, 500])

a = arr2[0]
b = arr2[2]
c = arr2[-1]

print(a)
print(b)
print(c)

100
300
500


In [ ]:
# Task 4 — Slicing Practice

arr3 = np.array([2,4,6,8,10,12])

a = arr3[1:2]
b = arr3[2:4]
c = arr3[-2:]

print(a)
print(b)
print(c)

[4]
[6 8]
[10 12]


In [ ]:
# Task 5 — Vectorization (Multiply)
# Task 6 — Vectorization (Addition)

arr4 = np.array([10,20,30,40])

a = arr4 * 5
b = arr4 + 5

print(a)
print(b)

[ 50 100 150 200]
[15 25 35 45]


In [ ]:
# Task 7 — Aggregation Functions

arr5 = np.array([5,15,25,35,45])

a = np.sum(arr5)
b = np.mean(arr5)
c = np.min(arr5)
d = np.max(arr5)

print(a)
print(b)
print(c)
print(d)

125
25.0
5
45


In [ ]:
# Task 8 — Create Arrays Using Functions

arr6 = np.arange(1,9).reshape(4,2)

print(arr6)
arr6.ndim

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


2

In [ ]:
# Task 9 — Type Checking

arr7 = np.array([1,2,3,4,5])
arr9 = np.multiply(arr7 , 2)
arr8 = [1,2,3,4,5]
sets = {1,2,3,4,5}

print(arr7.dtype)
print(type(arr7))
print(type(arr8))
print(type(sets))
print(type(arr9))

int64
<class 'numpy.ndarray'>
<class 'list'>
<class 'set'>
<class 'numpy.ndarray'>


In [ ]:
# Task 10 — Mini Challenge (Important)

# Create an array of 6 numbers of your choice
# Then:
# multiply by 2
# add 3
# find mean
# find max
# Do all operations using NumPy, not loops.

arr10 = np.arange(1,7)

mul = arr10 * 2
add = arr10 + 3
mean = np.mean(arr10)
min = np.min(arr10)
max = np.max(arr10)

print(arr10)
print(mul)
print(add)
print(mean)
print(min)
print(max)

[1 2 3 4 5 6]
[ 2  4  6  8 10 12]
[4 5 6 7 8 9]
3.5
1
6


# PHASE -2 NUMPY (2-D ARRAYS)

In [ ]:
arr_2d = np.array([[1,2,3] , [4,5,6]])

print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
# checking attributes of an 2D array

np.shape(arr_2d)
np.size(arr_2d)
np.ndim(arr_2d)

2

In [ ]:
# Indexing of an 2-D Arrays

a = arr_2d[1,0]   # Accessing the elements in arrays
b = arr_2d[0]     # Accessing the Rows in the 2-D Array
c = arr_2d[:,1]   # Accessing the Columns in the 2-D Array

print(a)
print(b)
print(c)

4
[1 2 3]
[2 5]


In [ ]:
# Task 1
# Create a 2×3 array and print:
# shape
# ndim

arr_2d = np.array([[1,2,3] , [4,5,6]])

print(arr_2d)
print(np.shape(arr_2d))
print(np.ndim(arr_2d))

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [ ]:
# Task 2
# Create a 3×3 array and print:
# first row
# second column

arr_2d_2 = np.array([[11,12,13] , [14,15,16] ,[17,18,19]])

a = arr_2d_2[0]
b = arr_2d_2[:,1]

print(arr_2d_2)
print("First row :",a)
print("Second column :",b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
First row : [11 12 13]
Second column : [12 15 18]


In [ ]:
# Task 3

# Create a zeros array of size 4×4.

zeros_arr = np.zeros((4,4))

print(zeros_arr)
print(np.ndim(zeros_arr))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


In [ ]:
# Task 4

# Create a ones array of size 2×5.

ones_arr = np.ones((2,5))

print(ones_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Task 5

# Create numbers from 10 to 50 using arange().

arange_arr = np.arange(10 ,50)

# a = arange_arr.reshape(4,5,2)

print(arange_arr)
# print(a)
# np.ndim(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Task 6

# Create 5 evenly spaced numbers between 0 and 100 using linspace().

linspace_arr = np.linspace(0 , 100 , num = 5 , dtype = int)

print(linspace_arr)

[  0  25  50  75 100]


In [ ]:
# Task 7

# Generate 6 random numbers between 0 and 1.

random_num = np.random.rand(6)


print(random_num)

[0.46981889 0.12431921 0.63943919 0.20135466 0.26690002 0.60359474]


In [ ]:
# Task 8

# Generate 5 random integers between 1 and 50.

random_arr = np.random.randint(1,50 , 5)

print(random_arr)

[28 30 40 16 22]


In [ ]:
# Task 9

# Create a 2D array and multiply all elements by 3.

arr_2d_3 = np.array([[1,2,3] , [4,5,6]])

multiply = arr_2d_3 * 3

print(multiply)

[[ 3  6  9]
 [12 15 18]]


In [ ]:
# Task 10 (Mini Real-World)

# Create marks of 4 students in 3 subjects (2D array) and find:
# average marks
# highest marks

marks = np.random.randint(10,50 ,size =(4,3))

average = np.mean(marks)
highest = np.max(marks)

print(marks)
print(average)
print(highest)
# print(marks[:,1])
# print(marks[3 ,1])

[[48 40 34]
 [15 24 43]
 [17 46 13]
 [48 10 14]]
29.333333333333332
48
[40 24 46 10]
10


# PHASE -3 (NUMPY)
Topics:

Reshaping arrays

Flattening arrays

Axis concept (very important)

Real-world style exercises

In [ ]:
# Task 1

# Create numbers 1–16 and reshape into 4×4.

arr_2D = np.arange(1,17).reshape(4,4)

print(arr_2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# Task 2

# Create numbers 1–9 and reshape into 3×3.

arr_2D_2 = np.arange(1,10).reshape(3,3)

print(arr_2D_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Task 3

# Flatten a 3×3 array.

flatten_arr = arr_2D.flatten()

print(flatten_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
# Task 4

# Create a 2×3 array and print sum of all elements.

sum_arr = np.arange(1 , 7).reshape(2,3)

print(sum_arr)
print(np.sum(sum_arr))

[[1 2 3]
 [4 5 6]]
21


In [ ]:
# Task 5

# Find row-wise sum using axis=1.

arr_3d = np.arange(1 , 21).reshape(4,5)

row_sum = np.sum(arr_3d , axis = 1)

print(arr_3d)
print(row_sum)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[15 40 65 90]


In [ ]:
# Task 6

# Find column-wise sum using axis=0.

arr_3d2 = np.arange(10 , 40).reshape(5,6)

column_sum = np.sum(arr_3d2 , axis = 0)

print(arr_3d2)
print(column_sum)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]
[110 115 120 125 130 135]


In [ ]:
# Task 7

# Create a marks table (3 students, 4 subjects) and find:
# average of each student

marks_table = np.arange(30 , 42).reshape(3, 4)

average = np.mean(marks_table , axis = 1 )

print(marks_table)
print("average of each student-",average)

[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]
average of each student- [31.5 35.5 39.5]


In [ ]:
# Task 8

# Using same table, find:
# highest marks in each subject

highest = np.max(marks_table, axis = 0)
print("Highest marks in each subject - ",highest)


Highest marks in each subject -  [38 39 40 41]


In [ ]:
# Task 9

# Create a random 3×3 array and reshape into 1×9

random_arr = np.random.randint(10 , 19 , size= (3,3))

reshape_arr = random_arr.reshape(1,9)

print(random_arr)
print(reshape_arr)

[[12 16 18]
 [10 18 11]
 [15 14 13]]
[[12 16 18 10 18 11 15 14 13]]


In [ ]:
# Task 10 (Real-world)

# Create salary data of 5 employees for 3 months:
# Find:
# average salary per employee
# average salary per month


salary_data = np.arange(1,16).reshape(5 , 3)

avg_sal = np.mean(salary_data , axis = 1 , dtype = int)
avg_mon = np.mean(salary_data , axis = 0 , dtype = int)

print(salary_data)
print("Average Salary -", avg_sal)
print("Average Month -", avg_mon)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Average Salary - [ 2  5  8 11 14]
Average Month - [7 8 9]
